== ZSTs

What do you think will be the output of this code?

[source,rust]
----
use std::mem::size_of;

struct Struct;

enum Enum { }

fn main() {
    println!("{}", size_of::<Struct>());
    println!("{}", size_of::<Enum>());
    println!("{}", size_of::<()>());
    println!("{}", size_of::<!>());
}
----

== ZSTs

Yeah, correct:

[listing]
----
error[E0658]: the `!` type is experimental
   |
   |     println!("{}", size_of::<!>());
   |                              ^
   |
   = note: see issue #35121 for more information
   = help: add `#![feature(never_type)]` to the crate attributes to enable
----

== ZSTs

[source,rust]
----
#![feature(never_type)]

use std::mem::size_of;

struct Struct;

enum Enum { }

fn main() {
    println!("{}", size_of::<Struct>());
    println!("{}", size_of::<Enum>());
    println!("{}", size_of::<()>());
    println!("{}", size_of::<!>());
}
----

== ZSTs

Yeah, all those types are *literally empty*:

[listing]
----
0
0
0
0
----

== ZSTs

ZST stands for *zero-sized type*.

== ZSTs

ZST stands for *zero-sized type*.

\... and they are hella useful!

== ZSTs

For instance, the `()` (called `unit type`) is used by the Rust's standard library to implement `HashSet`, reusing code
from `HashMap`:

[source,rust]
----
pub struct HashSet<T, S = RandomState> {
    map: HashMap<T, (), S>,
}
----

Since both Rust and LLVM know that such map contains only keys, all the additional code gets striped out - yay
*zero-cost abstractions*!

== ZSTs

By the way, `()` is both a value, and a type:

[source,rust]
----
fn main() {
               // vv value
    let foo: () = ();
          // ^^ type

    println!("{:?}", foo); // ()
}
----

== ZSTs

There exists a similar type, `!` (called `never type`), which serves a similar purpose, with one difference: you can't
obtain a value of this type.

== ZSTs

Let's talk: `Result<String, ()>`.

== ZSTs

Let's talk: `Result<String, ()>`:

[source,rust]
----
fn print_me(val: Result<String, ()>) {
    match val {
        Ok(val) => println!("ok: {:?}", val),
        Err(val) => println!("err: {:?}", val),
    }
}

fn main() {
    print_me(Ok("pancake".into())); // ok: "pancake"
    print_me(Err(()));              // err: ()
}
----

== ZSTs

Let's talk: `Result<String, !>`.

== ZSTs

Let's talk: `Result<String, !>`:

[source,rust]
----
fn print_me(val: Result<String, !>) {
    match val {
        Ok(val) => println!("ok: {:?}", val),
        Err(val) => println!("err: {:?}", val),
    }
}

fn main() {
    print_me(Ok("pancake".into()));
    print_me(Err(!)); // compile-time error
}
----

For `Result<String, !>` there's _no way_ to construct the `Err` variant.

[.compact]
== ZSTs

As an example, we can use `!` to implement a non-failing `FromStr`:

[source,rust]
----
use std::str::FromStr;

struct Person(String);

impl FromStr for Person {
    type Err = !;

    fn from_str(str: &str) -> Result<Self, !> {
        Ok(Person(
            str.into()
        ))
    }
}

fn main() {
    let Ok(person) = Person::from_str("Tommy Wiseau");

    // ^ no need to `.unwrap()`, because Rust understands
    // ^ that the `Err` variant cannot be possibly constructed

    println!("Oh hi, {}!", person.0);
}
----

[.compact]
== ZSTs

As another example, we _will be able to_ use `!` (called `never type`) to implement a non-failing `FromStr`:

[source,rust]
----
use std::str::FromStr;

struct Person(String);

impl FromStr for Person {
    type Err = !;

    fn from_str(str: &str) -> Result<Self, !> {
        Ok(Person(
            str.into()
        ))
    }
}

fn main() {
    let Ok(person) = Person::from_str("Tommy Wiseau");

    // ^ no need to `.unwrap()`, because Rust understands
    // ^ that the `Err` variant cannot be possibly constructed

    println!("Oh hi, {}!", person.0);
}
----

== ZSTs

Currently the compiler cannot yet fully reason about the `!`:

[listing]
----
error[E0005]: refutable pattern in local binding: `Err(_)` not covered
    |
    |     let Ok(person) = Person::from_str("Tommy Wiseau");
    |         ^^^^^^^^^^ pattern `Err(_)` not covered
----

The work on this feature is still ongoing though, so fingers crossed it gets merged soon!

== DSTs

DST stands for *dynamically-sized type*.

== DSTs

DST stands for *dynamically-sized type*.

You've for sure had the chance to use them tons of times:

- `str` (but not `&str` or `String`),
- `[T]` (but not `[T; n]`, `&[T]` or `Vec<T>`),
- `dyn Trait` (but not `&dyn Trait`).

== DSTs

DST stands for *dynamically-sized type*.

You've for sure had the chance to use them tons of times:

- `str` (but not `&str` or `String`),
- `[T]` (but not `[T; n]`, `&[T]` or `Vec<T>`),
- `dyn Trait` (but not `&dyn Trait`).

\... but there's also _one_ more.

== DSTs

What's the size of this type?

[source,rust]
----
struct NamedSlice<'a, T> {
    name: String,
    slice: &'a [T],
}
----

== DSTs

What's the size of this type?

[source,rust]
----
struct NamedSlice<'a, T> {
    name: String,
    slice: &'a [T],
}
----

24 bytes for `String` + 8 bytes for `&[T]` + padding = *40 bytes*.

(counted using `std::mem::size_of()` on a x86-64)

== DSTs

What's the size of _this_ type?

[source,rust]
----
struct NamedSlice<T> {
    name: String,
    slice: [T], // look, ma! no reference
}
----

== DSTs

What's the size of _this_ type?

[source,rust]
----
struct NamedSlice<T> {
    name: String,
    slice: [T],
}
----

First things first: *this is legal*; it's fine for a struct's _last_ field to be unsized.

== DSTs

What's the size of _this_ type?

[source,rust]
----
struct NamedSlice<T> {
    name: String,
    slice: [T],
}
----

First things first: *this is legal*; it's fine for a struct's _last_ field to be unsized.

Second things second: *this struct is `!Sized`*.

== DSTs

[source,rust]
----
use std::mem::size_of;

struct NamedSlice<T> {
    name: String,
    slice: [T],
}

fn main() {
    println!("{}", size_of::<NamedSlice<String>>());
}
----

== DSTs

[listing]
----
error[E0277]: the size for values of type `[String]` cannot be
              known at compilation time
    |
    |     println!("{}", size_of::<NamedSlice<String>>());
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                    doesn't have a size known at
    |                    compile-time
----

== DSTs

[source,rust]
----
struct NamedSlice<T> {
    name: String,
    slice: [T],
}

fn main() {
    let ns = NamedSlice {
        name: "named".into(),
        slice: [1, 2, 3] as _,
    };
}
----

== DSTs

[listing]
----
error[E0277]: the size for values of type `[_]` cannot be known
              at compilation time
   |
   |       let ns = NamedSlice {
   |  ______________^
   | |         name: "named".into(),
   | |         slice: [1, 2, 3] as _,
   | |     };
   | |_____^ doesn't have a size known at compile-time
----