#!/bin/bash

set -e

DOC_NAME=$1

if [[ -z "$DOC_NAME" ]]; then
    echo "error: missing document name"
    exit 1
fi

docker run \
    --rm \
    -v "$(pwd)/$DOC_NAME:/mnt" \
    -v "$(pwd)/_assets:/mnt/_assets" \
    -u`id -u $USER` \
    asciidoctor-pdf \
        ./presentation.adoc \
        --template-require ./template.js \
        -r asciidoctor-kroki

# The HTML file generated by `asciidoctor-pdf.js` contains references to `/mnt` - if we properly strip them, the
# generated HTML file can be properly accessed from a local browser
sed -i 's/\/mnt\///g' "$DOC_NAME/presentation.html"
