#!/usr/bin/env bash

set -e

echo '[+] Building presentation'

docker run \
    --rm \
    -v "$(pwd):/mnt" \
    -v "$(pwd)/../_assets:/mnt/_assets" \
    -u`id -u $USER` \
    asciidoctor-pdf \
        ./presentation.adoc \
        --template-require ./template.js \
        -r asciidoctor-kroki

# The HTML file generated by `asciidoctor-pdf.js` contains references to `/mnt` - if we properly strip them, the
# generated HTML file can be properly accessed from a local browser
echo '[+] Cleaning-up `presentation.html`'

sed -i 's/\/mnt\///g' "presentation.html"

echo '[+] Finished'
echo
echo 'Built artifacts:'
echo ' -  presentation.html'
echo ' -  presentation.pdf'
