== home-manager

[.prompter]
--
That's the last software that I want to show you, and it's meant for two types of people: configuration freaks and
people who don't know yet that are configuration freaks.

The question `home-manager` answers is: how can I declaratively install and configure software?
--

== home-manager

[.prompter]
--
Unless you already have a custom dotfiles repository, it might be a bit difficult to picture what's all the fuzz about,
so let's focus on a specific example: you want to install & configure `vim`.

On systems violating basic human rights such as Gentoo or Mac, it's a two-step operation: first you install the software
imperatively (for instance by running `apt install vim`), then you configure it (usually by modifying some stuff inside
the `.config` directory).

This has a dead-grave drawback: as months go by, you start gathering lots of small, incremental improvements to your
configuration and after a while it gets troublesome to, say, synchronize vim's configuration between your private and
work machine.

That gets especially gruesome & nasty when apart from the configuration files, you have to keep a list of additional
tools - like `fzf` or `oh-my-zsh`.

Before `home-manager`, I've never managed to get it right, and I vividly remember baby tears coming to my eyes as I was
trying to re-create my `emacs`-'s configuration at work.
--

`vim`

== home-manager

[.prompter]
--
With `home-manager`, you configure your environment using a single Nix expression that defines both the software _and_
configuration you want to get.

For example, this is how I've got my `vim` configured; since I'm not that much of a vim-guy, it's a rather modest
configuration, but it shows the overall concept.

When I change something in here, I launch `home-manager switch` in my terminal and it downloads the required software
and configures it appropriately.
--

[source,nix]
----
{ ... }: {
  programs = {
    vim = {
      enable = true;

      extraConfig = ''
        filetype plugin indent on
        set tabstop=4
        set shiftwidth=4
        set expandtab
      '';
    };
  };
}
----

[.compact.no-title]
== home-manager

[.prompter]
--
`home-manager` supports lots of various software - that's my `vscode` and, as you can see, I'm able to configure the
plugins I want to have installed.
--

[source,nix]
----
{ ... }: {
  programs = {
    vscode = {
      enable = true;

      extensions = with pkgs.vscode-extensions; [
        bbenoist.Nix
      ] ++ pkgs.vscode-utils.extensionsFromVscodeMarketplace [
        {
          name = "sort-lines";
          publisher = "Tyriar";
          version = "1.9.0";
          sha256 = "0l4wibsjnlbzbrl1wcj18vnm1q4ygvxmh347jvzziv8f1l790qjl";
        }
        {
          name = "vscode-opencl";
          publisher = "galarius";
          version = "0.6.5";
          sha256 = "1w6g8q5x72dy8g5hbrzr9kpsv7m2nnjarszdp69g37dbpmsrdcn2";
        }
      ];
    };
  };
}
----

[.compact.no-title]
== home-manager

[.prompter]
--
This example is a bit more fun - it configures a terminal emulator named `kitty` with a theme downloaded from GitHub and
a specific font.

Bonus: the font is automatically downloaded too.

Before Nix, I'd used git submodules for downloading the theme, and my unqualified memory for remembering to install
`Fira Code`.
--

[source,nix]
----
{ pkgs, ... }:

let
  kitty-themes = builtins.fetchGit {
    url = "https://github.com/dexpota/kitty-themes.git";
    rev = "fca3335489bdbab4cce150cb440d3559ff5400e2";
  };

in
{
  programs = {
    kitty = {
      enable = true;

      font.package = pkgs.fira-code;

      extraConfig = ''
        include ${kitty-themes}/themes/gruvbox_dark.conf

        kitty_mod ctrl+alt

        font_size 12.0
        font_family FiraCode-Light

        /* ... */
      '';
    };
  };
}
----

[.compact.no-title]
== home-manager

[.prompter]
--
One of the most elaborate configurations I have is the one for `zsh` and `oh-my-zsh` - you can see it installs powerline
fonts, installs some plugins, and configures stuff like autosuggestions and autojump.

Before Nix, here - too - I'd used git submodules for pinning down oh-my-zsh with some plugins and theme, and it was
similarly awkward in long-term usage.
--

[source,nix]
----
{ pkgs, ... }:

let
  k = builtins.fetchGit { /* ... */ };

in
{
  fonts.fonts = with pkgs; [ powerline-fonts ];

  programs = {
    autojump.enable = true;

    zsh = {
      enable = true;
      autocd = true;
      enableAutosuggestions = true;
      enableCompletion = true;

      oh-my-zsh = {
        enable = true;

        plugins = [
          "autojump"
          /* ... */
        ];

        extraConfig = ''
          COMPLETION_WAITING_DOTS="true"
          DISABLE_AUTO_TITLE="true"
          FZF_BASE="$(fzf-share)"
          /* ... */
        '';
      };
    };
  };
}
----

== home-manager

[.prompter]
--
What I've just shown you wasn't a comprehensive list - overall, I'm using home-manager to configure i3, polybar, rofi,
ssh, keybase, lorri, Rust, taskwarrior, picom, and lots of other software.

While the synchronizing capabilities are great, what I love about this Nix and home-manager combo the most is that I'm
both not afraid to try other configurations and that I don't keep hack-on-a-hack-on-a-hack inside my zshrc anymore; my
configuration stopped giving me this chilling jenga-that's-about-to-fall-down feeling.

When I want to check out a different theme or plugin, I just modify that Nix expression, launch `home-manager switch`
and optionally `git reset` followed by another `home-manager switch` to roll-back to the previous state.

So even if you have just one computer and don't care about keeping anything in sync, `home-manager` is still worth
trying out, be it just to clean-up all of your dotfiles.

As with all of the previous software, `home-manager` - too - has mastered the art of integration: it doesn't matter
whether you're working on Arch or Mac, `home-manager` will most likely fit to your workflow.
--

[.skip]
== home-manager

[.prompter]
--
Personally I'm using `home-manager` together with `NixOS`, which - next to applications - allows me to declaratively
configure drivers, systemctl units, docker and libvirt, remote mounts, and lots of other stuff... but, heart to heart:
while I do think that Nix as a package manager is absolutely fantastic eye-opening tool everyone should checkout out,
NixOS - as an entire operating system - is a tad different beast.

Because of this unorthodox, functional approach, lacking documentation and a rather small number of online tutorials,
NixOS is challenging to get into and, consequently, it's a frustrating experience for many (of which some I know in
person!).

That being said: _I_'ve been using NixOS for a couple of months and I wouldn't switch back even for Graham's number of
dollars - being able to fearlessly upgrade and rollback my entire system's configuration has left a permanent mark on my
mind and I'm totally a NixOS-occultist at this point.
--